#!/usr/bin/env bash
# nproxy install.sh — heap size configuration for NODE_OPTIONS
#
# Detects total RAM, asks user for preferred --max-old-space-size,
# writes ~/.nproxy.sh with a reusable variable.
# Re-run anytime to change the configuration.
set -e

NPROXY_DIR="$(cd "$(dirname "$0")" && pwd)"
NPROXY_JS="$NPROXY_DIR/node/nproxy.js"
NPROXY_ENV="$HOME/.nproxy.sh"
BASH_ALIASES="$HOME/.bash_aliases"

# ---- Detect ----
TOTAL_MB=$(awk '/MemTotal/{printf "%.0f", $2/1024}' /proc/meminfo 2>/dev/null || echo 0)
if [ "$TOTAL_MB" -lt 512 ]; then
  echo "Error: could not detect total RAM or RAM < 512MB"
  exit 1
fi
PCT75_MB=$(( TOTAL_MB * 3 / 4 ))
OC_DEFAULT_MB=8192

# ---- Ask heap size ----
cat << INFO

=== nproxy install ===
  Proxy:      $NPROXY_JS
  Total RAM:  ${TOTAL_MB}MB

Select --max-old-space-size (V8 heap limit):
  1) ${PCT75_MB}MB (75% of total RAM)
  2) ${OC_DEFAULT_MB}MB (OpenClaude default)
  3) Custom value
  4) Dynamic (compute at shell start via /proc/meminfo)
INFO
read -p "Choice [1]: " CHOICE
CHOICE=${CHOICE:-1}

case "$CHOICE" in
  1) HEAP_MB=$PCT75_MB ;;
  2) HEAP_MB=$OC_DEFAULT_MB ;;
  3) read -p "Enter heap size in MB: " HEAP_MB
     [ "$HEAP_MB" -gt 0 ] 2>/dev/null || { echo "Invalid"; exit 1; } ;;
  4) HEAP_MB="dynamic" ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

# ---- Write config snippet ----
rm -f "$NPROXY_ENV"

cat > "$NPROXY_ENV" << ENVEOF
# nproxy config — generated by install.sh, re-run to reconfigure
# Heap: ${HEAP_MB}MB (total RAM: ${TOTAL_MB}MB)
#
# Usage in aliases:
#   alias npro='source "$HOME/.nproxy.sh" && NODE_OPTIONS="\$NPROXY_NODE_OPTIONS" NPROXY_TEXT=passthrough'
#   alias myapp='npro /path/to/app'

ENVEOF

if [ "$HEAP_MB" = "dynamic" ]; then
  cat >> "$NPROXY_ENV" << ENVEOF
NPROXY_NODE_OPTIONS="--expose-gc --max-old-space-size=\$(( \$(awk '/MemTotal/{printf "%.0f", \$2/1024}' /proc/meminfo) * 3 / 4 )) -r $NPROXY_JS"
ENVEOF
else
  echo "NPROXY_NODE_OPTIONS=\"--expose-gc --max-old-space-size=$HEAP_MB -r $NPROXY_JS\"" >> "$NPROXY_ENV"
fi

chmod 644 "$NPROXY_ENV"

# ---- Source in .bash_aliases ----
MARKER="# nproxy (install.sh)"
if [ -f "$BASH_ALIASES" ] && grep -qF "$MARKER" "$BASH_ALIASES" 2>/dev/null; then
  echo "Already sourced in $BASH_ALIASES"
else
  echo ""
  echo "Add to $BASH_ALIASES:"
  echo "  $MARKER"
  echo "  [ -f \"$NPROXY_ENV\" ] && source \"$NPROXY_ENV\""
  read -p "Automatically append? [Y/n]: " APPEND
  APPEND=${APPEND:-y}
  if [[ "$APPEND" =~ ^[Yy] ]]; then
    echo "" >> "$BASH_ALIASES"
    echo "$MARKER" >> "$BASH_ALIASES"
    echo "[ -f \"$NPROXY_ENV\" ] && source \"$NPROXY_ENV\"" >> "$BASH_ALIASES"
    echo "Appended."
  fi
fi

# ---- Detect target binaries ----
OPENCODE_PATH=""
OPENCLAUDE_PATH=""
for CMD in opencode openclaude; do
  CMD_PATH="$(command -v "$CMD" 2>/dev/null || true)"
  if [ -n "$CMD_PATH" ] && [ -x "$CMD_PATH" ]; then
    case "$CMD" in
      opencode)   OPENCODE_PATH="$CMD_PATH" ;;
      openclaude) OPENCLAUDE_PATH="$CMD_PATH" ;;
    esac
  fi
done

# ---- Transparent binary wrapper ----
echo ""
echo "=== Transparent nproxy wrapper ==="
echo "Replace a binary with a wrapper that automatically"
echo "runs through nproxy. Just type the command as usual."
echo ""

WRAP_BIN=""
WRAP_BIN_NAME=""
if [ -n "$OPENCODE_PATH" ]; then
  echo "Detected: opencode ($OPENCODE_PATH)"
  echo "  → wrapper launches nproxy-run.sh --pty"
  echo ""
  read -p "Set up transparent wrapper for opencode? [Y/n]: " WRAP_OPENCODE
  WRAP_OPENCODE=${WRAP_OPENCODE:-y}
  if [[ "$WRAP_OPENCODE" =~ ^[Yy] ]]; then
    WRAP_BIN="$OPENCODE_PATH"
    WRAP_BIN_NAME="opencode"
  fi
fi

if [ -z "$WRAP_BIN_NAME" ] && [ -n "$OPENCLAUDE_PATH" ]; then
  echo "Detected: openclaude ($OPENCLAUDE_PATH)"
  echo "  → wrapper injects NODE_OPTIONS (requires --pty if non-Node)"
  echo ""
  read -p "Set up transparent wrapper for openclaude? [Y/n]: " WRAP_OC
  WRAP_OC=${WRAP_OC:-y}
  if [[ "$WRAP_OC" =~ ^[Yy] ]]; then
    WRAP_BIN="$OPENCLAUDE_PATH"
    WRAP_BIN_NAME="openclaude"
  fi
fi

if [ -n "$WRAP_BIN" ] && [ -n "$WRAP_BIN_NAME" ]; then
  # Resolve real binary path (follow symlinks)
  REAL_BIN="$(readlink -f "$WRAP_BIN" 2>/dev/null || echo "$WRAP_BIN")"

  # Determine backup location
  if [ "$REAL_BIN" != "$WRAP_BIN" ]; then
    # WRAP_BIN is a symlink: replace symlink with wrapper, real binary stays
    IS_SYMLINK=1
    BACKUP_BIN="" # no backup needed, just remove symlink
  else
    IS_SYMLINK=0
    BACKUP_BIN="${WRAP_BIN%/*}/${WRAP_BIN_NAME}.real"
  fi

  # Check if already wrapped
  HEADER=$(head -1 "$WRAP_BIN" 2>/dev/null || true)
  if echo "$HEADER" | grep -q "nproxy wrapper"; then
    echo "  Already wrapped: $WRAP_BIN"
  else
    echo ""
    echo "  Installing wrapper for $WRAP_BIN_NAME..."
    if [ $IS_SYMLINK -eq 0 ]; then
      echo "  Backing up original to $BACKUP_BIN"
    else
      echo "  Replacing symlink $WRAP_BIN → wrapper (real binary at $REAL_BIN)"
    fi

    if [[ "$WRAP_BIN_NAME" == "opencode" ]]; then
      # Check node-pty
      PTY_FLAG=""
      if node -e "require('node-pty')" 2>/dev/null; then
        PTY_FLAG="--pty"
      else
        echo ""
        echo "  node-pty not found. opencode (Go binary) needs PTY mode for stdin/stdout flow control."
        echo "  Options:"
        echo "    1) Install node-pty now (npm install -g node-pty)"
        echo "    2) Use pipe mode (no TTY, stdin/stdout relay only)"
        echo "    3) Skip wrapper setup"
        read -p "  Choice [1]: " PTY_CHOICE
        PTY_CHOICE=${PTY_CHOICE:-1}
        case "$PTY_CHOICE" in
          1)
            echo "  Installing node-pty..."
            npm install -g node-pty 2>&1 || { echo "  node-pty install failed."; PTY_FLAG=""; }
            PTY_FLAG="--pty"
            ;;
          2) PTY_FLAG="" ;;
          *) echo "  Skipped."; WRAP_BIN="" ;;
        esac
      fi
    fi

    if [ -n "$WRAP_BIN" ]; then
      if [ $IS_SYMLINK -eq 0 ]; then
        # Move real binary to backup location
        mv "$REAL_BIN" "$BACKUP_BIN"
      else
        # Remove symlink
        rm -f "$WRAP_BIN"
      fi

      # Create wrapper script
      cat > "$WRAP_BIN" << WRAPINNER
#!/bin/bash
# nproxy wrapper for $WRAP_BIN_NAME — generated by install.sh
# Re-run install.sh or use nproxy-uninstall.sh to revert.
NPROXY_DIR="$NPROXY_DIR"
REAL_BIN="$REAL_BIN"
if node -e "require('node-pty')" 2>/dev/null; then
    exec "\$NPROXY_DIR/nproxy-run.sh" --pty "\$REAL_BIN" "\$@"
else
    exec "\$NPROXY_DIR/nproxy-run.sh" passthrough "\$REAL_BIN" "\$@"
fi
WRAPINNER
      chmod 755 "$WRAP_BIN"
      echo "  Wrapper created: $WRAP_BIN"
      if [ $IS_SYMLINK -eq 0 ]; then
        echo "  Original backed up: $BACKUP_BIN"
      else
        echo "  Original binary: $REAL_BIN (unchanged)"
      fi
      echo "  Now type '$WRAP_BIN_NAME' to run through nproxy."

      # Save wrapper info for uninstall
      WRAPPER_INFO="$HOME/.nproxy_wrapper"
      echo "WRAP_BIN=$WRAP_BIN" > "$WRAPPER_INFO"
      echo "BACKUP_BIN=$BACKUP_BIN" >> "$WRAPPER_INFO"
      echo "REAL_BIN=$REAL_BIN" >> "$WRAPPER_INFO"
      echo "IS_SYMLINK=$IS_SYMLINK" >> "$WRAPPER_INFO"
      echo "WRAP_BIN_NAME=$WRAP_BIN_NAME" >> "$WRAPPER_INFO"
      echo "Wrapper info saved to $WRAPPER_INFO"
    fi
  fi
fi

# ---- LD_PRELOAD setup (optional) ----
echo ""
echo "=== LD_PRELOAD execve hook (optional) ==="
echo "Extra layer: intercepts execve() at the OS level via LD_PRELOAD."
echo "Useful for environments where NODE_OPTIONS is ignored (e.g. Bun)."
echo ""
read -p "Set up LD_PRELOAD execve hook? [y/N]: " LD_SETUP
LD_SETUP=${LD_SETUP:-n}
if [[ "$LD_SETUP" =~ ^[Yy] ]]; then
  LD_SO="$NPROXY_DIR/ld_preload/nproxy_ld.so"
  if [ ! -f "$LD_SO" ]; then
    echo "Building nproxy_ld.so..."
    make -C "$NPROXY_DIR/ld_preload" 2>&1 || { echo "Build failed."; LD_SETUP="n"; }
  fi
  if [[ "$LD_SETUP" =~ ^[Yy] ]]; then
    # Add to ~/.nproxy.sh
    echo "" >> "$NPROXY_ENV"
    echo "# LD_PRELOAD execve hook" >> "$NPROXY_ENV"
    echo "export NPROXY_LD_TARGETS=\"${WRAP_BIN_NAME:-opencode},node\"" >> "$NPROXY_ENV"
    echo "export NPROXY_LD_NPROXY=\"$NPROXY_DIR/nproxy-run.sh\"" >> "$NPROXY_ENV"
    echo "export LD_PRELOAD=\"$LD_SO\"\$LD_PRELOAD:+:\$LD_PRELOAD" >> "$NPROXY_ENV"
    echo "LD_PRELOAD configured. Active after shell restart or 'source $NPROXY_ENV'."
  fi
fi

# ---- Remote sync (optional) ----
echo ""
read -p "Sync to remote machine (192.168.3.14)? [y/N]: " SYNC
if [[ "$SYNC" =~ ^[Yy] ]]; then
  ssh mmixx@192.168.3.14 "mkdir -p \"$NPROXY_DIR/ld_preload\"" 2>/dev/null || true
  scp -r "$NPROXY_DIR/ld_preload" "mmixx@192.168.3.14:$NPROXY_DIR/ld_preload" 2>/dev/null
  scp "$NPROXY_ENV" "mmixx@192.168.3.14:$NPROXY_ENV" 2>/dev/null
  scp "$BASH_ALIASES" "mmixx@192.168.3.14:$BASH_ALIASES" 2>/dev/null
  [ -f "$HOME/.nproxy_wrapper" ] && scp "$HOME/.nproxy_wrapper" "mmixx@192.168.3.14:$HOME/.nproxy_wrapper" 2>/dev/null
  echo "Synced."
fi

# ---- Done ----
echo ""
echo "Done. File: $NPROXY_ENV"
echo ""
echo "Example aliases (add to ~/.bash_aliases):"
echo ""
echo "  # Generic Node.js app"
echo "  alias npro='source \$HOME/.nproxy.sh && NODE_OPTIONS=\"\$NPROXY_NODE_OPTIONS\" NPROXY_TEXT=passthrough'"
echo "  alias myapp='npro /path/to/app'"
echo ""
echo "  # openclaude with provider"
echo "  alias npro-deepseek='source \$HOME/.nproxy.sh && NODE_OPTIONS=\"\$NPROXY_NODE_OPTIONS\" NPROXY_TEXT=transform /usr/local/bin/openclaude --provider deepseek --model deepseek-chat'"
echo ""
echo "  # opencode (Go binary, transparent wrapper)"
echo "  # Already set up if you chose the wrapper option above."
echo "  # Otherwise:"
echo "  alias npro-opencode='$NPROXY_DIR/nproxy-run.sh --pty /usr/local/bin/opencode'"
echo ""
echo "  # systemd:"
echo "  #   source $HOME/.nproxy.sh && NODE_OPTIONS=\"\$NPROXY_NODE_OPTIONS\" ..."
echo ""
echo "  # Uninstall:"
echo "  #   $NPROXY_DIR/nproxy-uninstall.sh"
echo ""
echo "Run: source $BASH_ALIASES"
